### ISSUE TITLE
Incorrect syntax near 'ENGINE'. database error on setup

### ISSUE THREAD

**Issue by kirkaracha** [miniOrangeDev/saml-laravel-free#2]
I went to https://<my-host>/mo_admin, and on https://<my-host>/create_tables I get this error:

Setting up database for MiniOrange SAML SP for Laravel...
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'ENGINE'.

**Comment by ahmeraq** [comment]
I'm also facing the same issue. you fine any solution?

**Comment by miniOrangeDev** [comment]
Hi @kirkaracha and @ahmeraq ,

Hope you're both doing well! 🌟

A big shout-out to you for flagging this issue! Your keen eyes make all the difference. We're excited to share that our latest release has come to the rescue and this particular issue is now officially history! 🚀

We're incredibly grateful for your vigilance and input. If any more thoughts or questions pop up, you know where to find us.

Stay awesome and keep the collaboration going!
